# 第2章/aio_http_server/Dockerfile

# 指定该镜像基于python:3.8-alpine
FROM python:3.8-alpine
# 将 aio_http_server.py 文件拷贝到镜像中的 /opt 目录下
COPY aio_http_server.py /opt/
# 指定该镜像启动后的默认运行命令
CMD python /opt/aio_http_server.py
