version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - "./mariadb_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080